# ymlファイルのバージョン指定
version: '3'
# コンテナを定義
services:
    # サービス1
    db:
        image: postgres
    # サービス2
    webserver:
        # Dockerfileをビルド
        build: .
        command: python3 manage.py runserver 0.0.0.0:9000
        # マウント場所を指定
        volumes:
            - .:/app
        ports:
            - "9000:9000"
        # dbサービスが立ち上がってから起動するように指定
        depends_on:
            - db