# Generated by Django 2.0 on 2020-12-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one',
            name='dAnswer_2',
            field=models.CharField(default='選択肢2', max_length=200),
        ),
        migrations.AddField(
            model_name='one',
            name='dAnswer_3',
            field=models.CharField(default='選択肢3', max_length=200),
        ),
        migrations.AddField(
            model_name='one',
            name='dAnswer_4',
            field=models.CharField(default='選択肢4', max_length=200),
        ),
        migrations.AddField(
            model_name='one',
            name='dAnswer_5',
            field=models.CharField(default='選択肢5', max_length=200),
        ),
    ]
